/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        navy: '#16324F',
        'deep-navy': '#0D1F33',
        gold: '#F5A623',
        orange: '#E8871E',
        neutral: '#5A6B7B',
        canvas: '#F8FAFC',
        surface: 'var(--card)',
        success: 'var(--success)',
        danger: '#B91C1C',
        text: '#16324F',
        muted: '#5A6B7B',
        border: 'var(--border)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        'primary-light': 'var(--primary-light)',
        'primary-dark': 'var(--primary-dark)',
        'primary-soft': 'var(--primary-soft)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        'accent-light': 'var(--accent-light)',
        heading: 'var(--heading)',
        'muted-foreground': 'var(--muted-foreground)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        warning: 'var(--warning)',
        'warning-foreground': 'var(--warning-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        info: 'var(--info)',
        'info-foreground': 'var(--info-foreground)',
        'success-foreground': 'var(--success-foreground)',
        'dark-surface': 'var(--dark-surface)',
      },
      backgroundImage: {
        brand: 'var(--brand-gradient)',
        promo: 'var(--promo-gradient)',
      },
      borderRadius: { mk: '0.75rem' },
      boxShadow: { mk: '0 12px 30px rgba(13, 31, 51, 0.12)' },
    },
  },
  plugins: [],
};
